param(
    [Parameter(Mandatory)][ValidateRange(1,10000)][int]$StudentNumber,
    [Parameter(Mandatory)][int]$GroupNumber
)
$length = 16 + $StudentNumber
$bytes = 4 * $length
@"
# Personal assignment constants; generated by Configure.ps1
.eqv STUDENT_NUMBER $StudentNumber
.eqv GROUP_NUMBER $GroupNumber
.eqv ARRAY_LENGTH $length
.eqv ARRAY_BYTES $bytes
"@ | Set-Content -LiteralPath (Join-Path $PSScriptRoot 'params.inc') -Encoding utf8
